---

role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: k0s-controller
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - k0s
      - k0s_initial_controller
    volumes:
      - /tmp/molecule/k0s/controller:/opt
    network_mode: default
    docker_networks:
      - name: k8s
        ipam_config:
          - subnet: "10.21.0.0/24"
            gateway: "10.21.0.2"
    networks:
      - name: k8s
        ipv4_address: "10.21.0.10"

  - name: k0s-worker-1
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /tmp/molecule/k0s/worker-1:/opt:rw
    groups:
      - k0s
      - k0s_workers
    networks:
      - name: k8s
        ipv4_address: "10.21.0.21"

  - name: k0s-worker-2
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /tmp/molecule/k0s/worker-2:/opt:rw
    groups:
      - k0s
      - k0s_workers
    networks:
      - name: k8s
        ipv4_address: "10.21.0.22"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: "${MOLECULE_EPHEMERAL_DIRECTORY}/ansible_facts"

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
