---

- name: update facts to get latest information
  ansible.builtin.setup:

- name: create artifacts directory on ansible controller
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    state: directory
    path: "{{ k0s_artifacts_dir }}"
    mode: 0750

- name: get checksum of k0s config file on ansible controller
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ k0s_local_tmp_directory }}/admin.org"
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: k0s_admin_conf

- name: save config file to ansible controller
  become: true
  ansible.builtin.fetch:
    src: "{{ k0s_data_dir }}/pki/admin.conf"
    dest: "{{ k0s_local_tmp_directory }}/admin.org"
    flat: true
    validate_checksum: false
    mode: 0644
  register: fetched_k0s_admin_config
  when:
    - not k0s_admin_conf.stat.exists or
      ansible_local.k0s.config_checksum != k0s_admin_conf.stat.checksum

- name: detect k0s config file on ansible controller
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ k0s_artifacts_dir }}/k0s-kubeconfig.yml"
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: k0s_kubeconfig

- name: copy admin config file to k0s kubeconfig
  delegate_to: localhost
  become: false
  ansible.builtin.copy:
    src: "{{ k0s_local_tmp_directory }}/admin.org"
    dest: "{{ k0s_artifacts_dir }}/k0s-kubeconfig.yml"
    remote_src: true
    mode: 0644
  when:
    - not k0s_kubeconfig.stat.exists | default('false')

- name: read kubeconfig
  delegate_to: localhost
  become: false
  ansible.builtin.slurp:
    src: "{{ k0s_artifacts_dir }}/k0s-kubeconfig.yml"
  no_log: true
  register: k0s_kubeconfig_content

- name: check cluster url in k0s config file on ansible controller
  delegate_to: localhost
  become: false
  ansible.builtin.set_fact:
    k0s_valid_cluster_url: "{{ k0s_kubeconfig_content.content | b64decode | from_yaml | k0s_cluster_url(ansible_default_ipv4.address) }}"

- name: change controller IP
  when:
    - fetched_k0s_admin_config.changed | default('true') or
      not k0s_kubeconfig.stat.exists | default('false') or
      not k0s_valid_cluster_url
  block:
    - name: copy admin config file to k0s kubeconfig
      delegate_to: localhost
      become: false
      ansible.builtin.copy:
        src: "{{ k0s_local_tmp_directory }}/admin.org"
        dest: "{{ k0s_artifacts_dir }}/k0s-kubeconfig.yml"
        remote_src: true
        mode: 0644

    - name: set controller IP in kubeconfig
      delegate_to: localhost
      become: false
      ansible.builtin.replace:
        path: "{{ k0s_artifacts_dir }}/k0s-kubeconfig.yml"
        regexp: 'localhost'
        replace: "{{ ansible_default_ipv4.address }}"

...
