---

- name: detect binary file for k0s
  become: false
  delegate_to: "{{ k0s_delegate_to }}"
  stat:
    path: "{{ k0s_local_tmp_directory }}/k0s-{{ k0s_version }}.linux-amd64/k0s"
  register: stat_file_binary

- block:
    - name: propagate k0s binaries
      copy:
        src: "{{ k0s_local_tmp_directory }}/k0s"
        dest: "{{ k0s_install_path }}/"
        mode: 0755
        owner: "{{ k0s_system_user }}"
        group: "{{ k0s_system_group }}"
        remote_src: "{{ 'true' if k0s_direct_download else 'false' }}"

    - name: make files executable
      file:
        path: "{{ k0s_install_path }}/k0s"
        mode: 0755
        owner: "{{ k0s_system_user }}"
        group: "{{ k0s_system_group }}"

  when:
    - stat_file_binary.stat.exists

- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/k0s.fact
    mode: 0755

# - name: create link to binary
#   file:
#     src: "{{ k0s_install_path }}/k0s"
#     dest: "/usr/bin/k0s"
#     state: link
#     force: true
#     follow: false
#   notify:
#     - restart k0s

# - name: create systemd service unit
#   template:
#     src: "init/systemd/k0s.service.j2"
#     dest: "{{ systemd_lib_directory }}/k0s.service"
#     owner: root
#     group: root
#     mode: 0644
#   notify:
