---


- name: prepare
  include_tasks: prepare.yml
  tags:
    - download
    - install
    - configure
    - initial_configure

# - name: download binary
#   include_tasks: download.yml
#   when:
#     - not stat_k0s_binary.stat.exists
#   tags:
#     - download
#     - install
#
# - name: install
#   include_tasks: install.yml
#   tags:
#     - download
#     - install
#
# - name: configure k0s
#   include_tasks: configure/main.yml
#   tags:
#     - configure

- name: initial cluster configure
  include_tasks: configure/initial.yml
  tags:
    - initial_configure

# - name: configure
#   include_tasks: configure.yml
#
# - name: service
#   include_tasks: service.yml

...
