---

- name: d
  debug:
    msg:
      - "{{ k0s_nodes }}"
      - ""
      - "{{ k0s_initial_controller }}"
      - "{{ k0s_controllers | join(', ')  }}"
      - "{{ k0s_workers | join(', ') }}"
  run_once: true

- name: prepare
  include_tasks: prepare.yml
  tags:
    - k0s_prepare
    - k0s_download
    - k0s_install
    - k0s_configure

- name: download binary
  include_tasks: download.yml
  when:
    - not stat_k0s_binary.stat.exists
  tags:
    - k0s_download
    - k0s_install

- name: install
  include_tasks: install.yml
  tags:
    - k0s_download
    - k0s_install

- name: configure k0s
  include_tasks: configure/main.yml
  tags:
    - k0s_configure

- name: initial cluster configure
  include_tasks: configure/initial_controller.yml
  when:
    - ansible_hostname == k0s_nodes.initial_controller
  tags:
    - k0s_initial_configure

- name: controller configure
  include_tasks: configure/controller.yml
  when:
    - ansible_hostname in k0s_nodes.controllers
  tags:
    - k0s_controller

# - name: worker configure
#   include_tasks: configure/worker.yml
#   when:
#     - ansible_hostname in k0s_nodes.workers
#   tags:
#     - k0s_worker

- name: service
  include_tasks: service.yml
  tags:
    - k0s_service

- name: finalize
  include_tasks: finalize.yml
  when:
    - ansible_default_ipv4.address == k0s_nodes.initial_controller
  tags:
    - k0s_initial_configure

...
