---

- name: prepare
  include_tasks: prepare.yml
  tags:
    - k0s_prepare
    - k0s_download
    - k0s_install
    - k0s_configure

- name: reset k0s
  include_tasks: reset.yml
  when:
    - k0s_force is defined
    - k0s_force
  tags:
    - k0s_prepare

- name: download binary
  include_tasks: download.yml
  when:
    - not stat_k0s_binary.stat.exists
  tags:
    - k0s_download
    - k0s_install

- name: install
  include_tasks: install.yml
  tags:
    - k0s_download
    - k0s_install

- name: configure k0s
  include_tasks: configure/main.yml
  tags:
    - k0s_configure

- name: configure initial cluster k0s controller
  include_tasks: configure/initial_controller.yml
  when:
    - ansible_hostname == k0s_cluster_nodes.initial_controller or
      ansible_fqdn == k0s_cluster_nodes.initial_controller
  tags:
    - k0s_initial_controller

- name: configure k0s controller
  include_tasks: configure/controller.yml
  when:
    - k0s_cluster_nodes.controllers | count > 0
    - ansible_hostname in k0s_cluster_nodes.controllers or
      ansible_fqdn in k0s_cluster_nodes.controllers
  tags:
    - k0s_controller

- name: configure k0s worker
  include_tasks: configure/worker.yml
  when:
    - k0s_cluster_nodes.workers | count > 0
    - ansible_hostname in k0s_cluster_nodes.workers or
      ansible_fqdn in k0s_cluster_nodes.workers
  tags:
    - k0s_worker

- name: service
  include_tasks: service.yml
  tags:
    - k0s_service

- name: finalize
  include_tasks: finalize.yml
  when:
    - ansible_hostname == k0s_cluster_nodes.initial_controller or
      ansible_fqdn == k0s_cluster_nodes.initial_controller
  tags:
    - k0s_finalize

- name: k0s addons
  include_tasks: addons/main.yml
  run_once: true
  when:
    - ansible_hostname == k0s_cluster_nodes.initial_controller or
      ansible_fqdn == k0s_cluster_nodes.initial_controller
    - k0s_addons is defined
    - k0s_addons | count > 0
  tags:
    - k0s_addons

...
