---

- name: cluster members
  delegate_to: localhost
  run_once: true
  ansible.builtin.debug:
    msg:
      - "controllers : {{ k0s_cluster_nodes | k0s_cluster_members('controller') | join(', ') }}"
      - "workers     : {{ k0s_cluster_nodes | k0s_cluster_members('workers') | join(', ') }}"

- name: detect installed k0s binary
  ansible.builtin.stat:
    path: "{{ k0s_install_path }}/k0s"
  register: stat_k0s_binary

- name: reset full k0s config and data_dir
  k0s_reset:
    data_dir: "{{ k0s_data_dir }}"
    config: "{{ k0s_config_dir }}/k0s.yaml"
  register: _k0s_reset
  when:
    - stat_k0s_binary.stat.exists
  tags:
    - k0s_reset

- name: remove directories
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
    - "{{ k0s_install_path }}"
    - "{{ k0s_bin_path }}"
    - /etc/ansible/facts.d/k0s.fact

- name: reboot nodes
  when:
    - k0s_force
    - _k0s_reset is defined
    - _k0s_reset.rc is defined
    - _k0s_reset.rc == 0
  tags:
    - k0s_reset
  block:
    - name: reboot server
      ansible.builtin.shell: |
        sleep 2 && reboot
      failed_when: false
      changed_when: false
      async: 1
      poll: 5

    - name: wait for the reboot to complete if there was a change.
      ansible.builtin.wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

- name: reload facts
  ansible.builtin.setup:
  tags:
    - k0s_reset

...
