---

- name: reset full k0s config and data_dir
  k0s_reset:
    data_dir: "{{ k0s_data_dir }}"
    config: "{{ k0s_config_dir }}/k0s.yaml"
  register: k0s_reset

- name: d
  debug:
    msg: "{{ k0s_reset }}"

- name: reboot nodes
  block:
    - name: reboot server
      shell: sleep 2 && reboot
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
  when:
    - k0s_force
    - k0s_reset.rc == 0

- name: set k0s_force to false
  set_fact:
    k0s_force: false

- name: reload facts
  setup:

...
