---

- name: ensure k0s controller are enabled on boot
  become: true
  service:
    name: k0scontroller
    enabled: true
    state: started
  when:
    - ansible_hostname == k0s_cluster_nodes.initial_controller or
      ansible_fqdn == k0s_cluster_nodes.initial_controller
    # - not ansible_hostname in k0s_cluster_nodes.workers

- name: ensure k0s worker are enabled on boot
  become: true
  service:
    name: k0sworker
    enabled: true
    state: started
  when:
    - ansible_hostname in k0s_cluster_nodes.workers or
      ansible_fqdn in k0s_cluster_nodes.workers

...
