---

k0s_cluster_nodes:
  initial_controller: k0s-controller
  controllers: []
  workers: []

k0s_verbose: true

k0s_config_overwrites:
  spec:
    network:
      provider: calico
      clusterDomain: k0s.cluster
    api:
      address: 172.17.0.2
      externalAddress: controller.k0s.cluster
      sans:
        - controller.k0s.cluster
        - 172.17.0.2
    telemetry:
      enabled: false
    extensions:
      storage:
        type: openebs_local_storage

    # hosts:
    #   - role: controller
    #     installFlags:
    #       - --disable-components metrics-server
    # images:
    #   konnectivity:
    #     image: k8s.gcr.io/kas-network-proxy/proxy-agent
    #     version: v0.0.25
    #   metricsserver:
    #     image: k8s.gcr.io/metrics-server/metrics-server
    #     version: v0.5.0
    #   kubeproxy:
    #     image: k8s.gcr.io/kube-proxy
    #     version: v1.25.2
    #   coredns:
    #     image: k8s.gcr.io/coredns/coredns
    #     version: v1.7.0
    #   calico:
    #     cni:
    #       image: docker.io/calico/cni
    #       version: v3.18.1
...
