---

role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: k0s-controller-1
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - ALL
    tmpfs:
      - /run
      - /tmp
    groups:
      - k0s
      - k0s_initial_controller
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      # needs only by ubuntu 20.04
      # - /var/lib/docker/overlay2:/var/lib/docker/overlay2:Z
    network_mode: default
    docker_networks:
      - name: k8s
        ipam_config:
          - subnet: "10.20.0.0/24"
            gateway: "10.20.0.2"
    networks:
      - name: k8s
        ipv4_address: "10.20.0.10"

  - name: k0s-controller-2
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - ALL
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
      - /boot/config-4.19.0-21-cloud-amd64:/boot/config-4.19.0-21-cloud-amd64:ro
      # needs only by ubuntu 20.04
      # - /var/lib/docker/overlay2:/var/lib/docker/overlay2:Z
    groups:
      - k0s
      - k0s_controllers
    networks:
      - name: k8s
        ipv4_address: "10.20.0.11"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: "${MOLECULE_EPHEMERAL_DIRECTORY}/ansible_facts"

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
