---

- name: daemon-reload
  systemd:
    daemon_reload: true
    force: true
  notify: restart json_exporter
  when:
    - ansible_service_mgr == 'systemd'

- name: restart k0s_controller
  become: true
  service:
    name: k0scontroller
    state: restarted

- name: restart k0s_worker
  become: true
  service:
    name: k0sworker
    state: restarted

- name: wait for k8s apiserver
  wait_for:
    host: localhost
    port: 6443
    delay: 15
    timeout: 180
  when:
    - k0scontroller_started.changed or
      not k0scontroller_started.state == "started"

...
