---

ansible_user: root

k0s_force: false

k0s_data_dir: /opt/k0s

k0s_worker_on_controller: false

k0s_cluster_nodes:
  initial_controller: k0s-controller-1
  controllers: []
  workers: []

k0s_config: {}

...
