---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: k0s-controller
    hostname: k0s-controller
    box: trombik/ansible-debian-11-amd64
    memory: 1024
    cpus: 1
    interfaces:
      # `network_name` is the required identifier, other keys map to arguments.
      - network_name: private_network
        ip: 192.168.56.20
    # Dictionary of `config` options.
    config_options:
      vm.boot_timeout: 600
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml
      callbacks_enabled: profile_tasks

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
