---

- name: install
  hosts: all
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: ansible-k0s
      tags:
        - k0s_prepare
        - k0s_install
        - k0s_configure

- name: initial controller
  hosts: k0s-1
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: ansible-k0s
      tags:
        - k0s_initial_configure

- name: controller
  hosts: k0s-2
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: ansible-k0s
      tags:
        - k0s_controller

# - name: worker
#   hosts: k0s-3,k0s-4
#   any_errors_fatal: true
#   gather_facts: true
#
#   roles:
#     - role: ansible-k0s
#       tags:
#         - k0s_worker
