---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: k0s-controller
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - k0s
      - k0s_initial_controller

provisioner:
  name: ansible
  ansible_args:
    - --diff
  #   - -vvv
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml
      callbacks_enabled: profile_tasks

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra

