---

ansible_user: root

k0s_force: false

# k0s_initial_controller: "{{ groups | group_members('k0s_initial_controller') | first }}"
# k0s_controllers: "{{ groups | group_members('k0s_controllers') }}"
# k0s_workers: "{{ groups | group_members('k0s_workers') }}"

# k0s_cluster_nodes:
#   initial_controller: "{{ k0s_initial_controller }}"
#   controllers: "{{ k0s_controllers }}"
#   workers: "{{ k0s_workers }}"

k0s_data_dir: /opt/k0s

k0s_worker_on_controller: false

k0s_cluster_nodes:
  initial_controller: k0s-controller-1
  controllers:
    - k0s-controller-2
#    - k0s-controller-3
  workers: []
#    - k0s-worker-1

k0s_config:
  spec:
    api:
      address: "{{ ansible_default_ipv4.address }}"
      sans: "{{ k0s_cluster_nodes | k0s_cluster_members('controller') }}" # "{{ [k0s_cluster_nodes.initial_controller] + k0s_cluster_nodes.controllers }}"

    storage:
      etcd:
        peerAddress: "{{ ansible_default_ipv4.address }}"
  images:
    metricsserver: {}

...
