---

ansible_user: root

# k0s_initial_controller: "{{ groups | group_members('k0s_initial_controller') | first }}"
# k0s_controllers: "{{ groups | group_members('k0s_controllers') }}"
# k0s_workers: "{{ groups | group_members('k0s_workers') }}"

k0s_data_dir: /opt/k0s

k0s_worker_on_controller: true

k0s_cluster_nodes:
  initial_controller: k0s-controller
  controllers: []
  workers:
    - k0s-worker-1
    - k0s-worker-2

# k0s_cluster_nodes:
#   initial_controller: "{{ k0s_initial_controller }}"
#   controllers: "{{ k0s_controllers }}"
#   workers: "{{ k0s_workers }}"

k0s_addons:

  kubeproxy:
    name: kube-proxy
    version: latest
    ipvs_scheduler: rr
    mode: iptables
    directories:
      - kubeproxy
    templates:
      - kubeproxy/kubeproxy-sa.yml
      - kubeproxy/kubeproxy-rbac.yml
      - kubeproxy/kubeproxy-cm.yml
      - kubeproxy/kubeproxy-ds.yml

  kubedns:
    enabled: true
    name: kube-dns
    directories:
      - kubedns
    templates:
      - kubedns/kubedns-sa.yml
      - kubedns/kubedns-rbac.yml
      - kubedns/kubedns-cm.yml
      - kubedns/kubedns-svc.yml
      - kubedns/kubedns-dp.yml
      - kubedns/kubedns-autoscale-dp.yml

  dashboard:
    enabled: true
    name: kubernetes-dashboard
    directories:
      - dashboard
    templates:
      - dashboard/dashboard-sa.yml
      - dashboard/dashboard-rbac.yml
      - dashboard/dashboard-anonymous-rbac.yml
      - dashboard/dashboard-secret.yml
      - dashboard/dashboard-svc.yml
      - dashboard/dashboard-dp.yml

  metric_server:
    name: metric-server
    directories:
      - metric-server
    templates:
      - metric-server/metric-server-sa.yml
      - metric-server/metrics-server-rbac.yml
      - metric-server/metrics-apiservice.yml
      - metric-server/metrics-server-svc.yml
      - metric-server/metrics-server-dp.yml

  ingress_nginx:
    name: ingress-nginx
    directories:
      - ingress-nginx
    dependencies:
      - name: ingress-nginx
        kind: namespace
        files:
          - ingress-nginx/ingress-controller-ns.yml
    templates:
      - ingress-nginx/ingress-controller-sa.yml
      - ingress-nginx/ingress-controller-cm.yml
      - ingress-nginx/ingress-controller-rbac.yml
      - ingress-nginx/ingress-controller-svc.yml
      - ingress-nginx/ingress-controller-dp.yml

...
