---

- name: configure nodes
  debug:
    msg:
      - "{{ k0s_cluster_nodes.initial_controller }}"
  run_once: true

- name: define 'single' argument for a single node installation
  block:
    - name: get cluster members
      set_fact:
        k0s_extra_args: ["--single"]
      when:
        - k0s_cluster_nodes | k0s_cluster_members('all') | count == 1

- name: get k0s state
  k0s_status:
    state: initial-controller
    data_dir: "{{ k0s_data_dir }}"
  register: worker_k0s_state

- name: create k0s initial controller service with install command
  k0s_install:
    state: initial-controller
    force: "{{ k0s_force }}"
    config: "{{ k0s_config_dir }}/k0s.yaml"
    data_dir: "{{ k0s_data_dir }}"
    enable_worker: "{{ k0s_worker_on_controller | bool }}"
    arguments: "{{ k0s_extra_args | default([]) }}"
  notify:
    - daemon-reload
    - restart k0s_controller
  register: install_initial_controller_cmd

- name: arm specific systemd drop-in
  when:
    - (ansible_facts.architecture is search("arm") and
       ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")
  block:
    - name: create k0scontroller service drop-in directory
      file:
        path: /etc/systemd/system/k0scontroller.service.d
        state: directory
        mode: 0750

    - name: create overwrite.conf
      template:
        src: init/aarch64/systemd/overwrite.conf.j2
        dest: /etc/systemd/system/k0scontroller.service.d/overwrite.conf
        mode: 0644
      notify:
        - daemon-reload
        - restart k0s_controller

- name: flush handlers
  meta: flush_handlers

- name: Wait until the process is finished and {{ k0s_data_dir }}/pki/admin.conf was created
  delegate_to: "{{ k0s_cluster_nodes.initial_controller }}"
  ansible.builtin.wait_for:
    path: "{{ k0s_data_dir }}/pki/admin.conf"
    state: present

- name: start k0s controller
  service:
    name: k0scontroller
    state: started
  register: k0scontroller_started

- name: wait for k8s apiserver on port 6443
  delegate_to: "{{ k0s_cluster_nodes.initial_controller }}"
  wait_for:
    host: localhost
    port: 6443
    delay: 15
    timeout: 180
  when:
    - k0scontroller_started.changed or
      not k0scontroller_started.state == "started"

...
