---

- name: configure nodes
  debug:
    msg:
      - "{{ k0s_cluster_nodes.initial_controller }}"
  run_once: true

- name: create k0s initial controller service with install command
  k0s_install:
    state: controller
    force: "{{ k0s_force }}"
    config: "{{ k0s_config_dir }}/k0s.yaml"
    data_dir: "{{ k0s_data_dir }}"
    enable_worker: "{{ k0s_worker_on_controller | bool }}"
    arguments: "{{ k0s_extra_args | default([]) }}"
  notify:
    - daemon-reload
    - restart k0s_controller
  register: install_initial_controller_cmd

- name: arm specific systemd drop-in
  block:
    - name: create k0scontroller service drop-in directory
      file:
        path: /etc/systemd/system/k0scontroller.service.d
        state: directory
        mode: 0750

    - name: create overwrite.conf
      template:
        src: init/systemd/overwrite.conf.j2
        dest: /etc/systemd/system/k0scontroller.service.d/overwrite.conf
        mode: 0644
      notify:
        - daemon-reload
        - restart k0s_controller

  when:
    - (ansible_facts.architecture is search("arm") and
       ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: flush handlers
  meta: flush_handlers

- name: start k0s controller
  service:
    name: k0scontroller
    state: started

- name: wait for k8s apiserver
  wait_for:
    host: localhost
    port: 6443
    delay: 15
    timeout: 180

...
