---

# - name: configure nodes
#   ansible.builtin.debug:
#     msg:
#       - "{{ k0s_cluster_nodes }}"
#       - "{{ ansible_hostname }}"
#       - "{{ ansible_fqdn }}"
#   run_once: true

- name: create k0s directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"

- name: handle k0s config file
  when:
    - ansible_hostname in k0s_cluster_nodes | k0s_cluster_members('controller') or
      ansible_fqdn in k0s_cluster_nodes | k0s_cluster_members('controller')
  block:
    - name: create default k0s config
      k0s_config:
        state: create
        force: "{{ k0s_force }}"
        data_dir: "{{ k0s_data_dir }}"
        config_file: "{{ k0s_config_dir }}/k0s.yaml"
        config_overwrites: "{{ k0s_config | default({}) }}"
      register: default_k0s_config

...
