---

- name: configure nodes
  debug:
    msg:
      - "{{ k0s_cluster_nodes }}"
      - "{{ ansible_hostname }}"
      - "{{ ansible_fqdn }}"
  run_once: true

- name: create k0s directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"

- name: handle k0s config file
  block:
    - name: create default k0s config
      k0s_config:
        state: create
        force: "{{ k0s_force }}"
        data_dir: "{{ k0s_data_dir }}"
        config: "{{ k0s_config_dir }}/k0s.yaml"
      register: default_k0s_config
      when:
        - not k0s_use_custom_config

    - name: write the custom k0s config file
      become: true
      template:
        src: k0s/k0s.yml.j2
        dest: "{{ k0s_config_dir }}/k0s.yaml"
        mode: 0660
      when:
        - k0s_use_custom_config

  when:
    - ansible_hostname == k0s_cluster_nodes.initial_controller or
      ansible_fqdn == k0s_cluster_nodes.initial_controller
...
