---
- name: configure workers
  ansible.builtin.debug:
    msg:
      - "{{ k0s_cluster_nodes.workers | join(', ') }}"

- name: get k0s state
  k0s_status:
    state: worker
    data_dir: "{{ k0s_data_dir }}"
  register: worker_k0s_state

- name: install worker
  when:
    - not worker_k0s_state.state | default('missing') | string == "installed"
  block:
    - name: create join token on initial controller
      delegate_to: "{{ k0s_cluster_nodes.initial_controller }}"
      k0s_token:
        state: create
        role: worker
        expiry: "{{ k0s_token_expiry }}"
        data_dir: "{{ k0s_data_dir }}"
      register: worker_join_token

    - name: fail when no token returned
      ansible.builtin.fail:
        msg: "missing token to join workers"
      when:
        - not worker_join_token is defined or
          not worker_join_token.token is defined or
          worker_join_token.token | string | length == 0

    - name: write the k0s token file on worker
      ansible.builtin.copy:
        content: "{{ worker_join_token.token }}"
        dest: "{{ k0s_token_files.worker }}"
        owner: "{{ k0s_system_user }}"
        group: "{{ k0s_system_group }}"
        mode: 0600

    - name: create k0s worker service with install command
      k0s_install:
        state: worker
        force: "{{ k0s_force }}"
        data_dir: "{{ k0s_data_dir }}"
        token_file: "{{ k0s_token_files.worker }}"
        arguments: "{{ k0s_extra_args | default([]) }}"
      notify:
        - daemon-reload
        - restart k0s_worker
      register: install_worker_cmd

  rescue:
    - name: reset full k0s config and data_dir
      k0s_reset:
        data_dir: "{{ k0s_data_dir }}"
        config: "{{ k0s_config_dir }}/k0s.yaml"
      register: _k0s_reset

    - name: clean up the mess
      ansible.builtin.file:
        path: "{{ k0s_config_dir }}/k0s.yaml"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: "Error while join workers!"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: start k0s worker
  become: true
  ansible.builtin.service:
    name: k0sworker
    state: started
    enabled: true
  register: k0sworker_started
  notify:
    - wait for kublet on port 10250

...
