---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: k0s-controller-1
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    groups:
      - k0s
      - k0s_initial_controller
    volumes:
      - /tmp/molecule/k0s/controller:/opt
    network_mode: default
    docker_networks:
      - name: k8s
        ipam_config:
          - subnet: "10.20.0.0/16"
            gateway: "10.20.0.1"
    networks:
      - name: k8s
        ipv4_address: "10.20.0.10"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    # - -v
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml
      callbacks_enabled: profile_tasks

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
