---

# k0s_config_overwrites:
#   spec:
#     telemetry:
#       enabled: false
#     network:
#       clusterDomain: k0s.cluster
#     api:
#       address: 172.15.56.2
#       externalAddress: controller.k0s.cluster
#       sans:
#         - controller.k0s.cluster
#         # - worker-1.k0s.cluster
#         # - worker-2.k0s.cluster
#         - 172.15.56.2
#         - 10.21.0.2
#         - 127.0.0.1
...
