---

name: code linter

on:
  schedule:
    - cron: "20 4 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'plugins/**'
      - '!roles/**'
      - '!.github/workflows/test_role*.yml'
      - '.config/pycodestyle.cfg'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'plugins/**'
      - '!roles/**'
      - '!.github/workflows/test_role*.yml'
      - '.config/pycodestyle.cfg'

jobs:
  pep8:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
          - "3.12"

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pycodestyle

      - name: Lint code.
        run: |
          pycodestyle --config=.config/pycodestyle.cfg --statistics --count --exclude=test_default.py .

...
