---
name: multi controller

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-k0s'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:12
        python_version:
          - "3.11.3"
        ansible-version:
          - '6.7'
        scenario:
          - multi-controller

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-k0s'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"

        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
